[11:21:17 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"TypeError: nodemailer.createTransporter is not a function\n    at new EmailService (D:\\lab_node\\util\\email-service.js:6:39)\n    at Object.<anonymous> (D:\\lab_node\\util\\email-service.js:303:22)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)","name":"TypeError","message":"nodemailer.createTransporter is not a function"}
[11:57:48 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:59:37 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:59:37 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:04:48 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:04:48 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:05:28 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:05:42 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:05:54 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:309:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:49:37 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\auth.js:29:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[12:50:32 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: sendPasswordReset is not defined\n    at Object.<anonymous> (D:\\lab_node\\util\\email.js:933:5)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\controllers\\admin.js:15:83)","name":"ReferenceError","message":"sendPasswordReset is not defined"}
[15:57:00 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[15:57:19 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[15:57:53 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[15:58:24 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[15:58:31 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[15:59:37 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:00:20 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:00:22 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:01:07 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:01:23 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:01:43 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:02:11 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:02:25 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:02:56 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:02:58 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:03:38 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:03:56 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:05:49 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:06:12 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:06:26 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:07:28 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:07:34 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:08:16 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\contact.js:6:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[16:09:07 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:313:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:12:04 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:185:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[16:12:11 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:186:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[16:16:19 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:312:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[23:55:36 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:337:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[23:56:00 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:337:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[23:56:26 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:337:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[23:57:22 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:337:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[23:57:34 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:337:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[23:57:48 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:337:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[00:19:54 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:75:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[00:20:37 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:81:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[00:22:15 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:91:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[00:23:10 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:84:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
